version: '3'
services:
  app:
    build: .
    ports: 
      - 8080:8080 
    restart: always
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db          
    networks:
      - fullstack


  db:
    image: mysql:latest
    ports: 
      - 3305:3306
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD='password'
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack


volumes:
  api:
  database_mysql:                  

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
